### PR TITLE
Some scripts to generate Bullhorn announcements

### PR DESCRIPTION
**Pull request by mariolenz**
Some scripts to generate Bullhorn announcements and similar.

### CODE REVIEW

**Review by Andersson007 — COMMENTED** [review]
@mariolenz LGTM, thanks!

Should we maybe add a link to this README to https://github.com/ansible-community/community-topics/blob/main/community_topics_workflow.md#implementation-stage ?
something saying that for bullhorn announcements the scripts can be used
Thoughts?

**Review by gundalow — APPROVED** [review]
This is brilliant, thank you.

**Comment by mariolenz** [comment]
@Andersson007 I've just added a second commit. Did you mean something like this?

**Review by Andersson007 — APPROVED** [review]
@mariolenz yep, this is exactly what i meant, thanks! LGTM

**Pull request merged**
