### PR TITLE
Add topic process summary to README

### PR DESCRIPTION
**Pull request by felixfontein**
Basically what #3 said.

CC @Ompragash @Andersson007

### CODE REVIEW

**Review by Andersson007 — APPROVED** [review]
LGTM, thanks @felixfontein !

**Review by gundalow — APPROVED** [review]
Good idea, thank you

**Review by Ompragash — APPROVED** [review]
LGTM! Thanks, @felixfontein:)

**Review by tadeboro — APPROVED** [review]

**Comment by felixfontein** [comment]
@Andersson007 @gundalow @Ompragash @tadeboro thanks for reviewing this! :)

**Pull request merged**
