### PR TITLE
Stub out community_topics_workflow page

### PR DESCRIPTION
**Pull request by Andersson007**
Stub out community_topics_workflow page

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]
Let's maybe wait with merging until https://github.com/ansible/ansible-documentation/pull/1270 has been published on devel (i.e. tomorow).

**Comment by Andersson007** [comment]
@felixfontein sure thing

@mariolenz @felixfontein also we need to think what to do with `scripts` and `meetings`, ideas?
I think after we figure that out, we could close all the topics with a message asking the authors re-create them on the forum if relevant and archive the repo to reduce fragmentation.

**Comment by felixfontein** [comment]
>  I think after we figure that out, we could close all the topics with a message asking the authors re-create them on the forum if relevant and archive the repo to reduce fragmentation.

When we discussed moving things to the forum, we explicitly stated that existing discussions can stay here.

About the scripts: we still need them, and thus we need a place for them. If we want to archive this repo, we need to create a new repo for them.

**Comment by mariolenz** [comment]
@Andersson007 @felixfontein Since this is a PR to stub out community_topics_workflow page, maybe we should move the discussion about `scripts/` and `meetings/` and archiving this repo to a dedicated thread in the forum? This discussion looks off-topic here to me.

**Comment by Andersson007** [comment]
OK, folks, thanks! The forum topic SGTM.

**Pull request merged**
